In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


In [3]:
x,Y = load_iris(return_X_y=True,as_frame = True)




In [4]:
x0 = np.ones(len(x))*-1

x0_colum = pd.DataFrame(x0)

X = pd.concat([x0_colum,x],axis=1,ignore_index=True)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=32)

len(Y_test)


30

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Suponha que y_train contenha os rótulos 0, 1 e 2
y_train = Y_train.to_numpy() # Exemplo de dados

# Reshape para uma matriz de uma coluna, pois o OneHotEncoder espera um array 2D
y_train_reshaped = y_train.reshape(-1, 1)

# Criar uma instância do OneHotEncoder
encoder = OneHotEncoder(sparse=False, categories='auto')

# Ajustar e transformar os rótulos
y_train_one_hot = encoder.fit_transform(y_train_reshaped)

print(len(y_train_one_hot))
print(y_train_one_hot)


120
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]


/home/car/.local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Suponha que y_train contenha os rótulos 0, 1 e 2
y_test = Y_test.to_numpy() # Exemplo de dados

# Reshape para uma matriz de uma coluna, pois o OneHotEncoder espera um array 2D
y_test_reshaped = y_test.reshape(-1, 1)

# Criar uma instância do OneHotEncoder
encoder = OneHotEncoder(sparse=False, categories='auto')

# Ajustar e transformar os rótulos
y_test_one_hot = encoder.fit_transform(y_test_reshaped)

print(len(y_test_one_hot))
print(y_test_one_hot)

/home/car/.local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


30
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [102]:
np.random.seed(12)
w1 = np.random.uniform(low=-1, high=1, size=(3, 5))
w2 = np.random.uniform(low=-1, high=1, size=(2, 4))
w3 = np.random.uniform(low=-1, high=1, size=(3, 3))


In [103]:
n = 0.2
e = 1e-8
epoca = 0


In [104]:
def g(u):
    return np.maximum(0, u)
  

def g_dev(u):
  if u > 0:
    return 1

  else:
    return 0


In [105]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

def softmax_derivative(x):
    s = softmax(x)
    return s * (1 - s)  # A derivada da função softmax é softmax * (1 - softmax)


In [106]:
def erm(d,y):
  erro = 0
  for i in range(len(d)):
    for j in range(len(d[i])):
      erro += ((d[i][j] - y[j])**2)/2
    
  
  return erro/len(d)


In [107]:
i_1 = []
for j in range(len(w1)):
  z = np.dot(X_train.iloc[0,:],w1[j].T)
  i_1.append(z)

i_1


[0.07945598263058251, 5.4524987734286725, 4.560642969884382]

In [108]:
y_1 = g(i_1)

y_1 = np.insert(y_1,0,-1)

y_1

array([-1.        ,  0.07945598,  5.45249877,  4.56064297])

In [109]:
i_2 = []
for j in range(len(w2)):
  m = np.dot(y_1,w2[j].T)
  i_2.append(m)

i_2

[2.252086369431773, -7.832311933980734]

In [110]:
y_2 = g(i_2)

y_2 = np.insert(y_2,0,-1)

y_2

array([-1.        ,  2.25208637,  0.        ])

In [111]:
i_3 = []
for j in range(len(w3)):
  k = np.dot(y_2, w3[j].T)
  i_3.append(k)

i_3

[-0.08880015233550043, 1.4816170724517705, 0.44639413359966384]

In [30]:
y_3 = g(i_3)

y_3



array([1.20987035, 0.        , 0.3471906 ])

In [31]:
while True:
  errom = erm(y_train_one_hot,y_3)
  for w in range(1,len(X_train) - 1 ):
    ##Passo Forward
    i_1 = []
    for j in range(len(w1)):
      z = np.dot(X_train.iloc[w,:],w1[j])
      i_1.append(z)

    y_1 = g(i_1)
    y_1 = np.insert(y_1,0,-1)

    i_2 = []
    for j in range(len(w2)):
      m = np.dot(y_1,w2[j].T)
      i_2.append(m)

    y_2 = g(i_2)
    y_2 = np.insert(y_2,0,-1)

    i_3 = []
    for j in range(len(w3)):
      k = np.dot(y_2,w3[j].T)
      i_3.append(k)

    y_3 = g(i_3)
    ##Passo backward
    delta_3 = []

    for i in range(len(w3)):
      delta = (y_train_one_hot[w,i] - y_3[i]) * g_dev(i_3[i])

      delta_3.append(delta)

      
    for j in range(len(w3)):
      for i in range(len(w3[j])):
        w3[j][i] = w3[j][i] + n*(delta_3[j] * y_2[j])



    ####
    delta_2 = []

    for i in range(len(w2)):
      z = 0
      for k in range(len(w3)):
        z += np.dot(delta_3,w3[k])


      delta_2.append(z * g_dev(i_2[i]))



    for j in range(len(w2)):
      for i in range(len(w2[j])):
        w2[j][i] = w2[j][i] + n*(delta_2[j] * y_1[j])


    ######
    delta_1 = []

    for i in range(len(w1)):
      z = 0
      for k in range(len(w2)):
        z+= np.dot(delta_2,w2.T[k])

      delta_1.append(z * g_dev(i_1[i]))


    for j in range(len(w1)):
      for i in range(len(w1[j])):
        w1[j][i] = w1[j][i] + n*(delta_1[j] * X_train.iloc[w,i])


  em_atual = erm(y_train_one_hot,y_3)
  epoca +=1
  if abs(em_atual-errom) < e:
    break




In [112]:
y_3 = softmax(i_3)

y_3

array([0.13304181, 0.63975204, 0.22720614])

In [113]:
X_train_norm = pd.DataFrame(normalization(X_train))


In [75]:
def normalization(data):
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    data = scaler.fit_transform(data)

    return data

In [ ]:
import tensorflow as tf